# Generated by Django 4.1 on 2023-03-19 05:25

from django.db import migrations, models
import users.models
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(help_text='6-20个字符、密码不能与用户名相同、^[a-zA-Z](?![a-zA-Z]{5,19}$)([a-zA-Z0-9_.@$!%*#_~?&^]{5,19}$)', max_length=128, verbose_name='密码')),
                ('cell', models.CharField(max_length=11, verbose_name='手机号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('idcard', models.CharField(max_length=18, verbose_name='身份证件')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], help_text='M是男；F是女！', max_length=1, verbose_name='性别')),
                ('avatar', models.ImageField(default='users/default/default.jpg', upload_to=users.models.user_img_path, verbose_name='头像')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='居住地')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否已激活')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='是否已认证')),
                ('introduction', models.TextField(blank=True, max_length=200, verbose_name='个性签名')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(help_text='6-20个字符、密码不能与用户名相同、^[a-zA-Z](?![a-zA-Z]{5,19}$)([a-zA-Z0-9_.@$!%*#_~?&^]{5,19}$)', max_length=128, verbose_name='密码')),
                ('cell', models.CharField(max_length=11, verbose_name='手机号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('idcard', models.CharField(max_length=18, verbose_name='身份证件')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], help_text='M是男；F是女！', max_length=1, verbose_name='性别')),
                ('avatar', models.ImageField(default='users/default/default.jpg', upload_to=users.models.user_img_path, verbose_name='头像')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='居住地')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否已激活')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='是否已认证')),
                ('department', models.CharField(choices=[('D', '开发部门'), ('A', '审核部门')], max_length=1, verbose_name='部门')),
                ('state', models.CharField(choices=[('S', '病假'), ('P', '事假'), ('A', '年假')], max_length=1, verbose_name='状态')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否是超级管理员')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'admin',
                'verbose_name_plural': 'admins',
                'db_table': 'admin',
                'ordering': ('id',),
            },
            managers=[
                ('objects', users.utils.AdminUserManager()),
            ],
        ),
    ]
