# Generated by Django 4.1 on 2023-03-16 10:02

from django.db import migrations
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminuser',
            managers=[
                ('objects', users.utils.AdminUserManager()),
            ],
        ),
    ]
