# Generated by Django 4.1 on 2023-04-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_adminuser_username_alter_anyuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anyuser',
            old_name='is_anonymous',
            new_name='is_activate',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='cell',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='idcard',
            field=models.CharField(max_length=18, unique=True, verbose_name='身份证件'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='是否匿名者'),
        ),
        migrations.AlterField(
            model_name='anyuser',
            name='cell',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='anyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='anyuser',
            name='idcard',
            field=models.CharField(max_length=18, unique=True, verbose_name='身份证件'),
        ),
    ]
