# Generated by Django 4.1 on 2023-04-19 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'nav1',
                'verbose_name_plural': 'nav1s',
                'db_table': 'nav1',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Nav2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nav1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.nav1', to_field='name')),
            ],
            options={
                'verbose_name': 'nav2',
                'verbose_name_plural': 'nav2s',
                'db_table': 'nav2',
                'ordering': ('id',),
            },
        ),
    ]
