# Generated by Django 4.1 on 2023-04-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='category1',
        ),
        migrations.AddField(
            model_name='article',
            name='category2',
            field=models.ManyToManyField(to='article.nav2'),
        ),
    ]
