# Generated by Django 4.1 on 2023-06-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admintoken',
            table='admintoken',
        ),
        migrations.AlterModelTable(
            name='token',
            table='usertoken',
        ),
    ]
