# Generated by Django 4.1 on 2023-06-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_admintoken_table_alter_token_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
